
import { Language, TranslationSet, NGO, Project } from './types';

export const PRIMARY_GREEN = '#02A95C';
export const PLACEHOLDER_IMAGE = "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&q=80&w=1000";

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    home: 'Home',
    myDonations: 'My Gifts',
    about: 'About',
    notifications: 'Updates',
    oneTime: 'One-time',
    monthly: 'Monthly',
    donate: 'Donate Now',
    verified: 'Verified NGO',
    raisedOf: 'raised of',
    serviceFeeLabel: 'Service Fee',
    totalLabel: 'Total Payment',
    confirmDonation: 'Confirm Donation',
    ngoInstitution: 'Institution',
    topDonors: 'Top Donors',
    manageSubscription: 'Manage Subscriptions',
    adminLogin: 'Admin Access',
    enterOtp: 'Enter 6-digit OTP',
    searchPlaceholder: 'Search projects or NGOs...',
    donateToNgo: 'Donate to Institution',
    receipt: 'Donation Receipt',
    transactionId: 'TXN ID',
    date: 'Date',
    beneficiary: 'Beneficiary',
    close: 'Close',
    completedTitle: 'Success Stories',
    welcome: 'Welcome',
    featuredOperations: 'Featured Operations',
    browseNgos: 'Browse NGOs',
    topPriority: 'Top Priority',
    target: 'Target',
    details: 'Details',
    impactMade: 'Impact Made!',
    celebrationSub: 'Your contribution has been successfully processed. Thank you for empowering humanitarian change in Ethiopia.',
    done: 'Done',
    officialUpdates: 'Official Updates',
    noUpdates: 'No new updates yet',
    partnerOrg: 'Partner Organization',
    impactRaised: 'Impact Raised',
    theOperation: 'The Operation',
    recentDonors: 'Recent Donors',
    verifiedGift: 'Verified Gift',
    successTransfer: 'Successful Transfer',
    activeOperations: 'Active Operations',
    etbImpact: 'ETB Impact',
    allProjects: 'All Projects',
    funded: 'FUNDED',
    donationHistory: 'Donation History',
    noGifts: 'No gifts recorded yet',
    grossTotal: 'Gross Total',
    includesFee: 'Includes {fee} Service Fee',
    platformRules: 'Platform Rules',
    agreementReq: 'Agreement Required',
    acceptContinue: 'I Accept & Continue',
    termsSmallPrint: 'By continuing you agree to the full Terms of Service.',
    activeStatus: 'ACTIVE',
    nextPayment: 'Next',
    cancel: 'Cancel',
    supportGift: 'Support Gift',
    finalTotal: 'Final Total',
    confirmPay: 'Confirm & Pay',
    goBack: 'Go Back',
    recipientInst: 'Recipient Institution',
    amountEtb: 'Amount (ETB)',
    manage: 'Manage',
    subDetails: 'Subscription Details',
    recurringSub: 'Recurring Support',
    cancelSuccess: 'Subscription cancelled successfully'
  },
  am: {
    home: 'መነሻ',
    myDonations: 'ስጦታዎቼ',
    about: 'ስለ እኛ',
    notifications: 'ማሳወቂያዎች',
    oneTime: 'አንድ ጊዜ',
    monthly: 'በየወሩ',
    donate: 'አሁኑኑ ይለግሱ',
    verified: 'የተረጋገጠ NGO',
    raisedOf: 'ከተፈለገው ውስጥ',
    serviceFeeLabel: 'የአገልግሎት ክፍያ',
    totalLabel: 'ጠቅላላ ክፍያ',
    confirmDonation: 'ልገሳውን ያረጋግጡ',
    ngoInstitution: 'ተቋም',
    topDonors: 'ከፍተኛ ለጋሾች',
    manageSubscription: 'ምዝገባዎችን ያስተዳድሩ',
    adminLogin: 'የአስተዳዳሪ መግቢያ',
    enterOtp: 'ባለ 6 አሃዝ ኮድ ያስገቡ',
    searchPlaceholder: 'ፕሮጀክቶችን ወይም NGOዎችን ይፈልጉ...',
    donateToNgo: 'ለተቋሙ ይለግሱ',
    receipt: 'የልገሳ ደረሰኝ',
    transactionId: 'የመገበያያ መለያ',
    date: 'ቀን',
    beneficiary: 'ተጠቃሚ',
    close: 'ዝጋ',
    completedTitle: 'የተሳኩ ታሪኮች',
    welcome: 'እንኳን ደህና መጡ',
    featuredOperations: 'የተመረጡ ስራዎች',
    browseNgos: 'NGOዎችን ይመልከቱ',
    topPriority: 'ከፍተኛ ቅድሚያ',
    target: 'ግብ',
    details: 'ዝርዝር',
    impactMade: 'ለውጥ ተፈጥሯል!',
    celebrationSub: 'መዋጮዎ በተሳካ ሁኔታ ተጠናቅቋል። በኢትዮጵያ ውስጥ ሰብአዊ ለውጥን ስላበረታቱ እናመሰግናለን።',
    done: 'ተጠናቋል',
    officialUpdates: 'ይፋዊ መረጃዎች',
    noUpdates: 'እስካሁን ምንም አዲስ መረጃ የለም',
    partnerOrg: 'አጋር ድርጅት',
    impactRaised: 'የተገኘው ድጋፍ',
    theOperation: 'ስራው',
    recentDonors: 'የቅርብ ጊዜ ለጋሾች',
    verifiedGift: 'የተረጋገጠ ስጦታ',
    successTransfer: 'የተሳካ ዝውውር',
    activeOperations: 'ንቁ ስራዎች',
    etbImpact: 'የገንዘብ ተጽእኖ (ETB)',
    allProjects: 'ሁሉም ፕሮጀክቶች',
    funded: 'ተሟልቷል',
    donationHistory: 'የልገሳ ታሪክ',
    noGifts: 'እስካሁን የተመዘገበ ስጦታ የለም',
    grossTotal: 'ጠቅላላ ድምር',
    includesFee: 'የ{fee} አገልግሎት ክፍያን ይጨምራል',
    platformRules: 'የፕላትፎርሙ ደንቦች',
    agreementReq: 'ስምምነት ያስፈልጋል',
    acceptContinue: 'ተስማምቻለሁ ቀጥል',
    termsSmallPrint: 'በመቀጠልዎ በአገልግሎት ውሉ ተስማምተዋል።',
    activeStatus: 'ንቁ',
    nextPayment: 'ቀጣይ',
    cancel: 'ሰርዝ',
    supportGift: 'የድጋፍ ስጦታ',
    finalTotal: 'ጠቅላላ ድምር',
    confirmPay: 'አረጋግጥና ክፈል',
    goBack: 'ተመለስ',
    recipientInst: 'ተቀባይ ተቋም',
    amountEtb: 'መጠን (ETB)',
    manage: 'ያስተዳድሩ',
    subDetails: 'የምዝገባ ዝርዝሮች',
    recurringSub: 'ተደጋጋሚ ድጋፍ',
    cancelSuccess: 'ምዝገባው በተሳካ ሁኔታ ተሰርዟል'
  },
  or: {
    home: 'Mana',
    myDonations: 'Kennaa Koo',
    about: "Waa'ee",
    notifications: 'Oduu',
    oneTime: 'Yeroo Tokko',
    monthly: "Ji'aan",
    donate: 'Amma Gumaachi',
    verified: "NGO Mirkanaa'e",
    raisedOf: 'walitti qabame',
    serviceFeeLabel: 'Kaffaltii Tajaajilaa',
    totalLabel: 'Kaffaltii Waliigalaa',
    confirmDonation: 'Gumaacha Mirkanessi',
    ngoInstitution: 'Dhaabbata',
    topDonors: 'Gumaachitoota Gurguddoo',
    manageSubscription: 'Subscription Bulchi',
    adminLogin: 'Seensa Admin',
    enterOtp: 'OTP lakk. 6 galchi',
    searchPlaceholder: 'Barbaadi...',
    donateToNgo: 'Dhaabbataaf Gumaachi',
    receipt: 'Nagahee',
    transactionId: 'Lakk. Transaction',
    date: 'Guyyaa',
    beneficiary: 'Fayyadamoo',
    close: 'Cufi',
    completedTitle: 'Seenaa Milkaa\'inaa',
    welcome: 'Baga Dhufte',
    featuredOperations: 'Hojiiwwan Filataman',
    browseNgos: 'NGO Daawwadhu',
    topPriority: 'Dursi Ol’aanaa',
    target: 'Galma',
    details: 'Bal’ina',
    impactMade: 'Milkaa’ina!',
    celebrationSub: 'Gumaachi keessan milkaa’inaan xumurameera. Itoophiyaa keessatti jijjiirama namummaa gumaachuu keessaniif galatoomaa.',
    done: 'Xumurame',
    officialUpdates: 'Oduu Haaraa',
    noUpdates: 'Oduun haaraan hin jiru',
    partnerOrg: 'Dhaabbata Miillaa',
    impactRaised: 'Gumaacha Walitti Qabame',
    theOperation: 'Hojicha',
    recentDonors: 'Gumaachitoota Dhihoo',
    verifiedGift: 'Kennaa Mirkanaa’e',
    successTransfer: 'Tiraanisferii Milkaa’e',
    activeOperations: 'Hojiiwwan Hojjetamaa Jiran',
    etbImpact: 'ETB Gumaachame',
    allProjects: 'Projektoota Hunda',
    funded: 'GUTAMEERA',
    donationHistory: 'Seenaa Gumaachaa',
    noGifts: 'Gumaachi galmaa’e hin jiru',
    grossTotal: 'Waliigala Gumaachaa',
    includesFee: 'Kaffaltii tajaajilaa {fee} dabalata',
    platformRules: 'Seera Pilaatfoormichaa',
    agreementReq: 'Waliigalteen Barbaachisaadha',
    acceptContinue: 'Nan fudhadha Itti fufi',
    termsSmallPrint: 'Itti fufuun seera tajaajilaa hunda irratti waliigaluu keessan agarsiisa.',
    activeStatus: 'HOJJETAMAARA',
    nextPayment: 'Itti aanu',
    cancel: 'Haqi',
    supportGift: 'Kennaa Deeggarsaa',
    finalTotal: 'Kaffaltii Waliigalaa',
    confirmPay: 'Mirkanessi Kaffali',
    goBack: 'Deebi’i',
    recipientInst: 'Dhaabbata Fudhataa',
    amountEtb: 'Mamma (ETB)',
    manage: 'Bulchi',
    subDetails: 'Bal’ina Subscription',
    recurringSub: 'Deeggarsa Irra Deddeebii',
    cancelSuccess: 'Subscription milkaa’inaan haqameera'
  },
  ti: {
    home: 'ገዛ',
    myDonations: 'ህያዋተይ',
    about: 'ብዛዕባና',
    notifications: 'ሓበሬታታት',
    oneTime: 'ሓደ ግዜ',
    monthly: 'ወርሓዊ',
    donate: 'ሕጂ ለግሱ',
    verified: 'ዝተረጋገጸ NGO',
    raisedOf: 'ካብ ዝተደለየ',
    serviceFeeLabel: 'ክፍሊት ኣገልግሎት',
    totalLabel: 'ጠቕላላ ክፍሊት',
    confirmDonation: 'ልገሳ አረጋግጽ',
    ngoInstitution: 'ትካል',
    topDonors: 'ላዕለዎት ለጋሶት',
    manageSubscription: 'ምዝገባታት አተሓሕዝ',
    adminLogin: 'መእተዊ ኣመሓዳሪ',
    enterOtp: '6 ኣሃዝ ኮድ የእትው',
    searchPlaceholder: 'ድለዩ...',
    donateToNgo: 'ንትካል ለግሱ',
    receipt: 'መቀበሊ ልገሳ',
    transactionId: 'መፍለዪ ትራንዛክሽን',
    date: 'ዕለት',
    beneficiary: 'ተጠቃሚ',
    close: 'ዕጾ',
    completedTitle: 'ዝተዓወቱ ታሪኻት',
    welcome: 'እንኳዕ ብደሓን መጻእኹም',
    featuredOperations: 'ዝተመርጹ ስራሕቲ',
    browseNgos: 'ትካላት ርኣዩ',
    topPriority: 'ለዓለዋይ ቀዳምነት',
    target: 'ሸቶ',
    details: 'ዝርዝር',
    impactMade: 'ለውጢ ተፈጢሩ!',
    celebrationSub: 'ልገሳኹም ብዓወት ተዛዚሙ። ኣብ ኢትዮጵያ ሰብኣዊ ለውጢ ስለዘተባባዕኩም ነመስግን።',
    done: 'ተዛዚሙ',
    officialUpdates: 'ወግዓዊ ሓበሬታታት',
    noUpdates: 'ዛጊት ዝኾነ ሓድሽ ሓበሬታ የለን',
    partnerOrg: 'መሻርኽቲ ትካል',
    impactRaised: 'ዝተረኽበ ደገፍ',
    theOperation: 'እቲ ስራሕ',
    recentDonors: 'ናይ ቀረባ ግዜ ለጋሶት',
    verifiedGift: 'ዝተረጋገጸ ህያብ',
    successTransfer: 'ዝተዓወተ ምስግጋር',
    activeOperations: 'ንቑሕ ስራሕቲ',
    etbImpact: 'ጽልዋ ETB',
    allProjects: 'ኩሎም ፕሮጀክትታት',
    funded: 'ተማሊኡ',
    donationHistory: 'ታሪኽ ልገሳ',
    noGifts: 'ዛጊት ዝተመዝገበ ህያብ የለን',
    grossTotal: 'ጠቕላላ ድምር',
    includesFee: 'ናይ {fee} ክፍሊት ኣገልግሎት ይውስኽ',
    platformRules: 'ሕግታት ፕላትፎርም',
    agreementReq: 'ስምምዕ የድሊ',
    acceptContinue: 'ተሰማሚዐ ቀጽል',
    termsSmallPrint: 'ብምቕጻልኩም ኣብ ኩሉ ውዕላት ኣገልግሎት ተሰማሚዕኩም ኣለኹም።',
    activeStatus: 'ንቑሕ',
    nextPayment: 'ቀጻሊ',
    cancel: 'ሰርዝ',
    supportGift: 'ህያብ ደገፍ',
    finalTotal: 'ናይ መወዳእታ ክፍሊት',
    confirmPay: 'አረጋግጽን ክፈልን',
    goBack: 'ተመለስ',
    recipientInst: 'ተቐባሊ ትካል',
    amountEtb: 'መጠን (ETB)',
    manage: 'አተሓሕዝ',
    subDetails: 'ዝርዝር ምዝገባ',
    recurringSub: 'ተደጋጋሚ ደገፍ',
    cancelSuccess: 'ምዝገባ ብዓወት ተሰሪዙ'
  }
};

export const MOCK_NGOS: NGO[] = [
  {
    id: 'ngo-1',
    name: 'Ethiopian Red Cross',
    licenseNo: 'CH-2024-001',
    description: 'Providing emergency relief and community support across Ethiopia since 1935.',
    logo: 'https://picsum.photos/seed/redcross/200',
    coverImage: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    isSuspended: false,
    isFeatured: true,
    totalRaised: 1250000,
    joinedDate: '2023-01-15'
  },
  {
    id: 'ngo-2',
    name: 'Save the Children',
    licenseNo: 'CH-2024-002',
    description: 'Protecting and supporting children in need through education and healthcare.',
    logo: 'https://picsum.photos/seed/children/200',
    coverImage: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    isSuspended: false,
    isFeatured: false,
    totalRaised: 850000,
    joinedDate: '2023-03-20'
  }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    ngoId: 'ngo-1',
    title: { en: 'Drought Relief Borehole', am: 'የድርቅ መከላከያ የውሃ ጉድጓድ', or: 'Boolla Bishaan Hongee', ti: 'ዒላ ማይ ደርቂ' },
    description: { en: 'Building solar-powered boreholes for clean water in rural areas.', am: 'በገጠር አካባቢዎች ለንጹህ ውሃ የሚሆን በፀሐይ ኃይል የሚሰራ የውሃ ጉድጓድ መገንባት።', or: "Qe'ee baadiyyaatti boolla bishaan qulqulluu ijaaruu.", ti: 'ኣብ ገጠር ከባቢታት ንጽሩይ ማይ ዝኸውን ዒላ ማይ ምስራሕ።' },
    goalAmount: 500000,
    raisedAmount: 325000,
    images: ['https://images.unsplash.com/photo-1541810228801-d85f75bc195f?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1473615695634-d284ec918736?auto=format&fit=crop&q=80&w=800'],
    category: 'Water',
    isFeatured: true,
    donorsCount: 1420,
    status: 'urgent'
  },
  {
    id: 'p2',
    ngoId: 'ngo-2',
    title: { en: 'Rural Schools Library', am: 'የገጠር ትምህርት ቤቶች ቤተ መጻሕፍት', or: 'Mana Kitaaba Baadiyyaa', ti: 'ቤተ መጻሕፍቲ ገጠር' },
    description: { en: 'Providing books and reading materials to 50 rural schools.', am: 'ለ50 የገጠር ትምህርት ቤቶች መጻሕፍትን እና የንባብ ቁሳቁሶችን ማቅረብ።', or: "Mana barumsaa baadiyyaa 50'f kitaaba dhiyeessuu.", ti: 'ንን50 ኣብያተ ትምህርቲ ገጠር መጻሕፍቲ ምቕራብ።' },
    goalAmount: 200000,
    raisedAmount: 180000,
    images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800'],
    category: 'Education',
    isFeatured: false,
    donorsCount: 890,
    status: 'active'
  }
];
